print("Sinh vien: Nguyen Minh Hieu")
print("Mssv: 245752021610010")
print("*************************************")
ds = input("Nhập các từ: ").split()
max_word = max(ds, key=len)
print("Từ dài nhất là:", max_word)
